---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mapdotoro

<!-- badges: start -->
<!-- badges: end -->

Mapdotoro aim to prepared the Fluvial Corridor Toolbox data outputs to the shiny application mapdoapp.

## Installation

You can install the development version of mapdotoro from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("EVS-GIS/mapdotoro")
```

## Workflow

Testing dataset can be found

```{r}
library(dplyr)
library(sf)
library(tmap)
library(mapdotoro)

data(bassin_hydrographique)
data(region_hydrographique)
data(referentiel_hydro)
data(swaths)
```

Map dataset
```{r, eval = FALSE}
tmap::tmap_mode("view")
map <- tmap::tm_shape(bassin_hydrographique) +
  tmap::tm_polygons()+
tmap::tm_shape(region_hydrographique) +
  tmap::tm_polygons()+
tmap::tm_shape(swaths) +
  tmap::tm_polygons()+
tmap::tm_shape(referentiel_hydro) +
  tmap::tm_lines(col= "blue")
map
```

clean dataset
```{r}
swaths_data <- swaths %>% 
  dplyr::filter(VALUE == 2) # keep only valid swaths

sf::st_geometry(swaths_data) <- "geom" # standard geometry column

duplicated_swaths <- check_duplicate(swaths_data)
cleaned_swaths <- clean_duplicated(dataset = swaths_data,
                                   duplicated_dataset = duplicated_swaths)

```

```{r, eval = FALSE}
map + tmap::tm_shape(duplicated_swaths) + 
  tmap::tm_polygons(col = "red")
```












